version: "3"

services:
  web:
    image: project:0.0.1 # needs 'docker build -t project:0.0.1 .' first 
    restart: always
    container_name: web
    ports:
      - 8000:8000
    volumes:
      - ./sock/:/sock/
      - ./:/code
      - ./logs/:/logs/
    command: sh entrypoint.sh
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - django_nw

  worker:
    image: project:0.0.1
    restart: always
    container_name: worker
    command: "celery -A project worker -f /logs/worker.log -l DEBUG"
    depends_on:
      - web
    volumes:
      - ./logs/:/logs/
      - ./:/code
    env_file:
      - worker_env.txt
    networks:
      - django_nw

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443 
    volumes:
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf   # Change nginx/nginx-proxy-sample.conf to nginx-proxy.conf
      - ./frontend_app/dist:/var/www/frontend
      - ./sock/:/sock/
      - ./logs/nginx:/var/log/nginx
      - ./static:/static
      - ./media:/media
    depends_on:
      - web
      - worker
    networks:
      - django_nw
  
  db:
    image: mdillon/postgis:11-alpine
    container_name: db
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    ports: 
      - 5432:5432
    env_file:
      - pg_env.txt
    networks:
      - django_nw

  redis:
    image: redis:alpine
    restart: always
    container_name: redis
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - ./_redis_data:/var/lib/redis
      - ./redis/rc.local:/etc/rc.local
    networks:
      - django_nw

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-naxa1
    env_file: pg_env.txt
    ports:
      - "5051:80"
    restart: always
    depends_on:
      - db

  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins
    env_file: jenkins.env
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home

  # geoserver:
  #   image: kartoza/geoserver:2.19.0
  #   container_name: geoserver-naxa1
  #   env_file: geoserver_env.txt
  #   volumes:
  #     - geoserver-data:/opt/geoserver/data_dir
  #   ports:
  #     - "8600:8080"
  #   restart : on-failure
  #   depends_on:
  #     - db

networks:
  django_nw:
    driver: bridge
