version: '3.4'

services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-naxa1
    env_file: pg_env.txt
    ports:
      - "5051:80"
    restart: always
    depends_on:
      - db

  geoserver:
    image: kartoza/geoserver:2.19.0
    container_name: geoserver-naxa1
    env_file: geoserver_env.txt
    volumes:
      - geoserver-data:/opt/geoserver/data_dir
    ports:
      - "8600:8080"
    restart : on-failure
    depends_on:
      - db


  


volumes:
  postgres-data:
    name: postgres-data
  geoserver-data:
    name: geoserver-data
