# Generated by Django 3.2.3 on 2021-06-03 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_project_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='many_category',
            field=models.ManyToManyField(related_name='many_category', to='core.Category'),
        ),
    ]
